#!/bin/sh

### BEGIN INIT INFO
# Provides:          i2pd
# Required-Start:    $network $local_fs $remote_fs $time
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop the i2p router
# Description: i2p is a load-balanced unspoofable packet switching network
### END INIT INFO

# Author: Kill Your TV <killyourtv@i2pmail.org>

PATH="/sbin:/usr/sbin:/bin:/usr/bin"
DESC="I2P router daemon"
NAME="i2pd"
DAEMON="/usr/lib/i2pd/i2p"
DAEMON_HOME="/var/lib/i2pd"
DAEMON_ARGS=""
PIDFILE="/run/$NAME.pid"
USER="i2pd"

[ -x $DAEMON ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME
. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" --test > /dev/null \
    || return 1
  if [ ! -e ${DAEMON_HOME}/hosts.txt ]; then
      zcat /usr/share/doc/i2pd/examples/hosts.txt.gz > $DAEMON_HOME/hosts.txt
  fi
  if [ ! -d ${DAEMON_HOME}/certificates ]; then
    rm -rf ${DAEMON_HOME}/certificates
    cp -Rp /usr/lib/i2pd/certificates ${DAEMON_HOME}
  fi
  touch $PIDFILE
  chown ${USER}:${USER} $PIDFILE
  start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --chuid "$USER" -- \
    --service=1 --daemon=1 --log=1 $DAEMON_ARGS || return 2
}

do_stop()
{
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
  RETVAL="$?"
  [ "$RETVAL" = 2 ] && return 2
  start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
  [ "$?" = 2 ] && return 2
  rm -f $PIDFILE
  return "$RETVAL"
}

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
    do_start
    case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  stop)
  [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
    2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
  esac
  ;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  restart|force-reload)
  log_daemon_msg "Restarting $DESC" "$NAME"
  do_stop
  case "$?" in
    0|1)
    do_start
    case "$?" in
      0) log_end_msg 0 ;;
      1) log_end_msg 1 ;; # Old process is still running
      *) log_end_msg 1 ;; # Failed to start
    esac
    ;;
    *)
      # Failed to stop
    log_end_msg 1
    ;;
  esac
  ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
    exit 3
  ;;
esac

:
